import type { ApplicationCard, Opportunity, Watchlist } from "./types";

export const opportunities: Opportunity[] = [
  {
    id: "opp-1",
    title: "Fullstack Developer Internship",
    company: "Widya Matador",
    role: "Fullstack",
    role_specialization: "fullstack",
    category: "tech",
    location: "Depok",
    location_area: "jakarta_area",
    work_mode: "hybrid",
    duration: "3-6 bulan",
    salary_display: "Rp800.000",
    deadline: null,
    source_platform: "glints",
    source_url: "https://glints.com/id/opportunities/jobs/fullstack-developer-internship",
    score: 90,
    dashboard_quality: "high",
    extraction_depth: "full_detail",
    verification_level: "verified_detail",
    active_status: "active",
    summary_short: "Merancang API, mengembangkan arsitektur frontend dan backend website, serta membuat kode aplikasi.",
    first_seen: "2026-05-17",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-2",
    title: "Fullstack Developer IT Intern",
    company: "CRISBAR",
    role: "Fullstack",
    role_specialization: "fullstack",
    category: "tech",
    location: "Jakarta",
    location_area: "jakarta_area",
    work_mode: "remote",
    duration: null,
    salary_display: null,
    deadline: null,
    source_platform: "glints",
    source_url: "https://glints.com/id/opportunities/jobs/fullstack-developer-it-intern",
    score: 90,
    dashboard_quality: "high",
    extraction_depth: "full_detail",
    verification_level: "verified_detail",
    active_status: "active",
    summary_short: "Membangun aplikasi web mobile-first, sistem login, loyalty point, reward, dan referral.",
    first_seen: "2026-05-18",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-3",
    title: "Software Engineer Intern (Paid Internship)",
    company: "HITHINK TECHNOLOGY INDONESIA",
    role: "Software Engineering",
    role_specialization: "software",
    category: "tech",
    location: "Indonesia",
    location_area: "indonesia",
    work_mode: null,
    duration: null,
    salary_display: "Paid Internship",
    deadline: null,
    source_platform: "jobstreet",
    source_url: "https://www.jobstreet.co.id/job/123456",
    score: 80,
    dashboard_quality: "medium",
    extraction_depth: "listing_card",
    verification_level: "listed_only",
    active_status: "listed",
    summary_short: "Lowongan ditemukan dari listing Jobstreet dan perlu dicek detailnya di platform asli.",
    first_seen: "2026-05-16",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-4",
    title: "Frontend Developer Intern",
    company: "Meinhardt Group",
    role: "Frontend",
    role_specialization: "frontend",
    category: "tech",
    location: "Indonesia",
    location_area: "indonesia",
    work_mode: null,
    duration: null,
    salary_display: null,
    deadline: null,
    source_platform: "linkedin",
    source_url: "https://www.linkedin.com/jobs/view/123456789",
    score: 75,
    dashboard_quality: "medium",
    extraction_depth: "search_snippet",
    verification_level: "search_index_only",
    active_status: "unknown",
    summary_short: "Peluang frontend intern yang ditemukan dari halaman publik LinkedIn.",
    first_seen: "2026-05-18",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-5",
    title: "Backend Developer Intern",
    company: "PT Sigma Global Teknologi",
    role: "Backend",
    role_specialization: "backend",
    category: "tech",
    location: "Jakarta",
    location_area: "jakarta_area",
    work_mode: "onsite",
    duration: null,
    salary_display: null,
    deadline: null,
    source_platform: "glints",
    source_url: "https://glints.com/id/opportunities/jobs/backend-developer-intern",
    score: 85,
    dashboard_quality: "high",
    extraction_depth: "full_detail",
    verification_level: "verified_detail",
    active_status: "active",
    summary_short: "Mencari Backend Developer Intern yang antusias dan berminat di pengembangan web.",
    first_seen: "2026-05-17",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-6",
    title: "Internship Mobile Developer",
    company: "PT Qtera Mandiri",
    role: "Mobile",
    role_specialization: "mobile",
    category: "tech",
    location: "Jakarta",
    location_area: "jakarta_area",
    work_mode: "onsite",
    duration: null,
    salary_display: null,
    deadline: null,
    source_platform: "glints",
    source_url: "https://glints.com/id/opportunities/jobs/internship-mobile-developer",
    score: 85,
    dashboard_quality: "high",
    extraction_depth: "full_detail",
    verification_level: "verified_detail",
    active_status: "active",
    summary_short: "Magang mobile developer untuk pengembangan aplikasi Android menggunakan Kotlin.",
    first_seen: "2026-05-17",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-7",
    title: "Web Developer Intern",
    company: "MarviO",
    role: "Software Engineering",
    role_specialization: "web",
    category: "tech",
    location: "Yogyakarta",
    location_area: "yogyakarta",
    work_mode: "onsite",
    duration: null,
    salary_display: "Rp700.000",
    deadline: null,
    source_platform: "glints",
    source_url: "https://glints.com/id/opportunities/jobs/web-developer-intern",
    score: 90,
    dashboard_quality: "high",
    extraction_depth: "full_detail",
    verification_level: "verified_detail",
    active_status: "active",
    summary_short: "Membantu pengembangan website dan aplikasi digital.",
    first_seen: "2026-05-18",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-8",
    title: "Magang Web Developer Berbayar",
    company: "PT Bimasakti Multi Sinergi",
    role: "Fullstack",
    role_specialization: "fullstack",
    category: "tech",
    location: null,
    location_area: null,
    work_mode: null,
    duration: null,
    salary_display: null,
    deadline: null,
    source_platform: "jobstreet",
    source_url: "https://www.jobstreet.co.id/job/654321",
    score: 65,
    dashboard_quality: "medium",
    extraction_depth: "listing_card",
    verification_level: "listed_only",
    active_status: "listed",
    summary_short: "Lowongan ditemukan dari listing Jobstreet. Cek detail di platform asli.",
    first_seen: "2026-05-18",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-9",
    title: "Data Analyst Intern",
    company: "Kredito Group",
    role: "Data Analyst",
    role_specialization: "data",
    category: "data",
    location: "Jakarta",
    location_area: "jakarta_area",
    work_mode: "hybrid",
    duration: null,
    salary_display: "Rp1.200.000",
    deadline: "26 Mei 2026",
    source_platform: "glints",
    source_url: "https://glints.com/id/opportunities/jobs/data-analyst-intern",
    score: 72,
    dashboard_quality: "high",
    extraction_depth: "full_detail",
    verification_level: "verified_detail",
    active_status: "active",
    summary_short: "Membantu analisis data untuk mendukung pengambilan keputusan produk dan bisnis.",
    first_seen: "2026-05-16",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-10",
    title: "Product Manager Intern",
    company: "Gojek",
    role: "Product Manager",
    role_specialization: "product",
    category: "product",
    location: "Jakarta",
    location_area: "jakarta_area",
    work_mode: "hybrid",
    duration: "6 bulan",
    salary_display: null,
    deadline: null,
    source_platform: "dealls",
    source_url: "https://dealls.com/loker/product-manager-intern~gojek",
    score: 88,
    dashboard_quality: "high",
    extraction_depth: "full_detail",
    verification_level: "verified_detail",
    active_status: "active",
    summary_short: "Mendukung riset produk, prioritas backlog, dan koordinasi eksperimen fitur.",
    first_seen: "2026-05-18",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-11",
    title: "UI/UX Design Intern",
    company: "Tokopedia",
    role: "UI/UX",
    role_specialization: "ui_ux",
    category: "design",
    location: "Jakarta",
    location_area: "jakarta_area",
    work_mode: "hybrid",
    duration: "6 bulan",
    salary_display: null,
    deadline: null,
    source_platform: "dealls",
    source_url: "https://dealls.com/loker/ui-ux-design-intern~tokopedia",
    score: 82,
    dashboard_quality: "high",
    extraction_depth: "full_detail",
    verification_level: "verified_detail",
    active_status: "active",
    summary_short: "Membantu riset pengguna, wireframe, prototype, dan handoff desain ke tim produk.",
    first_seen: "2026-05-18",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-12",
    title: "Actuarial Internship Program",
    company: "Manulife Indonesia",
    role: "Actuarial",
    role_specialization: "actuarial",
    category: "actuarial",
    location: "Jakarta",
    location_area: "jakarta_area",
    work_mode: "hybrid",
    duration: "6.5 bulan",
    salary_display: null,
    deadline: "30 Juni 2026",
    source_platform: "generic",
    source_url: "https://careers.manulife.com/id/actuarial-internship-program",
    score: 86,
    dashboard_quality: "high",
    extraction_depth: "full_detail",
    verification_level: "verified_detail",
    active_status: "active",
    summary_short: "Program magang aktuaria untuk mendukung pricing, reserving, dan analisis portofolio asuransi.",
    first_seen: "2026-05-19",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-13",
    title: "Quality Assurance Intern",
    company: "Bukalapak",
    role: "Quality Assurance",
    role_specialization: "qa",
    category: "tech",
    location: "Bandung",
    location_area: "west_java",
    work_mode: "remote",
    duration: null,
    salary_display: null,
    deadline: null,
    source_platform: "kalibrr",
    source_url: "https://www.kalibrr.id/c/bukalapak/jobs/123/quality-assurance-intern",
    score: 78,
    dashboard_quality: "medium",
    extraction_depth: "full_detail",
    verification_level: "verified_detail",
    active_status: "active",
    summary_short: "Membantu membuat test case, menjalankan regression test, dan mendokumentasikan temuan bug.",
    first_seen: "2026-05-19",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-14",
    title: "Business Intelligence Intern",
    company: "Traveloka",
    role: "Business Intelligence",
    role_specialization: "data",
    category: "data",
    location: "Indonesia",
    location_area: "indonesia",
    work_mode: "remote",
    duration: "3 bulan",
    salary_display: "Rp1.500.000",
    deadline: null,
    source_platform: "linkedin",
    source_url: "https://www.linkedin.com/jobs/view/987654321",
    score: 74,
    dashboard_quality: "medium",
    extraction_depth: "search_snippet",
    verification_level: "search_index_only",
    active_status: "unknown",
    summary_short: "Peluang BI intern dari sumber publik untuk membantu dashboard, reporting, dan analisis metrik.",
    first_seen: "2026-05-19",
    last_verified_at: "2026-05-19",
  },
  {
    id: "opp-15",
    title: "Mobile Engineer Intern",
    company: "Amartha",
    role: "Mobile",
    role_specialization: "mobile",
    category: "tech",
    location: "Jakarta",
    location_area: "jakarta_area",
    work_mode: "hybrid",
    duration: null,
    salary_display: null,
    deadline: null,
    source_platform: "jobstreet",
    source_url: "https://www.jobstreet.co.id/job/789012",
    score: 70,
    dashboard_quality: "medium",
    extraction_depth: "listing_card",
    verification_level: "listed_only",
    active_status: "listed",
    summary_short: "Lowongan mobile engineer intern ditemukan dari listing. Cek detail di platform asli.",
    first_seen: "2026-05-19",
    last_verified_at: "2026-05-19",
  },
];

export const applications: ApplicationCard[] = [
  { id: "app-1", opportunity: opportunities[3], status: "saved", updated_at: "Hari ini, 09.20" },
  { id: "app-2", opportunity: opportunities[0], status: "saved", updated_at: "Kemarin, 14.12" },
  { id: "app-3", opportunity: opportunities[2], status: "applied", updated_at: "20 Mei 2026", applied_at: "20 Mei 2026" },
  { id: "app-4", opportunity: opportunities[4], status: "applied", updated_at: "19 Mei 2026", applied_at: "19 Mei 2026" },
  { id: "app-5", opportunity: opportunities[8], status: "screening", updated_at: "17 Mei 2026", applied_at: "15 Mei 2026" },
  { id: "app-6", opportunity: opportunities[10 - 1], status: "interview", updated_at: "21 Mei 2026", applied_at: "16 Mei 2026" },
  {
    id: "app-7",
    opportunity: {
      ...opportunities[1],
      id: "opp-ml",
      title: "Machine Learning Intern",
      company: "DANA",
      role: "AI/ML",
      role_specialization: "ai_ml",
      score: 92,
      summary_short: "Membantu eksperimen model machine learning untuk produk finansial digital.",
    },
    status: "technical_test",
    updated_at: "22 Mei 2026",
    applied_at: "18 Mei 2026",
  },
  {
    id: "app-8",
    opportunity: {
      ...opportunities[8],
      id: "opp-ds",
      title: "Data Scientist Intern",
      company: "Accenture",
      role: "Data Scientist",
      score: 88,
      source_platform: "kalibrr",
    },
    status: "offer",
    updated_at: "23 Mei 2026",
    applied_at: "14 Mei 2026",
  },
  { id: "app-9", opportunity: opportunities[7], status: "rejected", updated_at: "Kemarin, 18.30", applied_at: "12 Mei 2026" },
];

export const watchlists: Watchlist[] = [
  {
    id: "watch-1",
    title: "Frontend Intern Jakarta",
    roles: ["Frontend"],
    locations: ["Jakarta"],
    newCount: 4,
    lastRun: "Terakhir dicek hari ini",
  },
  {
    id: "watch-2",
    title: "Data Analyst Remote",
    roles: ["Data Analyst"],
    locations: ["Remote"],
    newCount: 2,
    lastRun: "Terakhir dicek hari ini",
  },
  {
    id: "watch-3",
    title: "Actuarial Internship",
    roles: ["Aktuaria"],
    locations: ["Indonesia"],
    newCount: 1,
    lastRun: "Terakhir dicek kemarin",
  },
];
